# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Menggunakan npm untuk mengelola dependensi
    directory: "/" # Lokasi file package.json
    schedule:
      interval: "weekly" # Dependabot akan memeriksa pembaruan setiap minggu
  - package-ecosystem: "github-actions" # Mengelola pembaruan GitHub Actions
    directory: "/" # Lokasi file workflow GitHub Actions (misalnya .github/workflows)
    schedule:
      interval: "weekly" # Memeriksa pembaruan untuk GitHub Actions setiap minggu
